<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Muni-Bouwer.Data\Muni-Bouwer.Data.csproj" />
    <ProjectReference Include="..\Muni-Bouwer.Entities\Muni-Bouwer.Entities.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Muni_Bouwer.Business</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
