// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muni_Bouwer.Data.Context;

#nullable disable

namespace Muni_Bouwer.Data.Migrations
{
    [DbContext(typeof(BouwerDbContext))]
    partial class BouwerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HorarioFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HorarioInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.AlumnoActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdActividad")
                        .HasColumnType("int");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdActividad");

                    b.HasIndex("IdAlumno");

                    b.ToTable("AlumnoActividades");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.AsistenciaAlumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdAlumnoActividad")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumnoActividad");

                    b.ToTable("AsistenciasAlumnos");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.AsistenciaDocente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdDocenteActividad")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdDocenteActividad");

                    b.ToTable("AsistenciasDocentes");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.DocenteActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdActividad")
                        .HasColumnType("int");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdActividad");

                    b.HasIndex("IdDocente");

                    b.ToTable("DocenteActividades");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Documentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaCarga")
                        .HasColumnType("date");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumno");

                    b.ToTable("Documentaciones");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.FichaMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enfermedades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumno")
                        .IsUnique();

                    b.ToTable("FichasMedicas");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaInscripcion")
                        .HasColumnType("date");

                    b.Property<int>("IdAlumnoActividad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumnoActividad");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaAlta")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaModificacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<int>("PermisosId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("PermisosId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolesPermisos", (string)null);
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuariosRoles", (string)null);
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Alumno", b =>
                {
                    b.HasBaseType("Muni_Bouwer.Entities.Models.Usuario");

                    b.Property<string>("NombreContactoEmergencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelContactoEmergencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Alumno");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Coordinador", b =>
                {
                    b.HasBaseType("Muni_Bouwer.Entities.Models.Usuario");

                    b.HasDiscriminator().HasValue("Coordinador");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Docente", b =>
                {
                    b.HasBaseType("Muni_Bouwer.Entities.Models.Usuario");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Docente");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.AlumnoActividad", b =>
                {
                    b.HasOne("Muni_Bouwer.Entities.Models.Actividad", "Actividad")
                        .WithMany("AlumnoActividades")
                        .HasForeignKey("IdActividad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Muni_Bouwer.Entities.Models.Alumno", "Alumno")
                        .WithMany("AlumnoActividades")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.AsistenciaAlumno", b =>
                {
                    b.HasOne("Muni_Bouwer.Entities.Models.AlumnoActividad", "AlumnoActividad")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdAlumnoActividad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlumnoActividad");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.AsistenciaDocente", b =>
                {
                    b.HasOne("Muni_Bouwer.Entities.Models.DocenteActividad", "DocenteActividad")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdDocenteActividad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocenteActividad");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.DocenteActividad", b =>
                {
                    b.HasOne("Muni_Bouwer.Entities.Models.Actividad", "Actividad")
                        .WithMany("DocenteActividades")
                        .HasForeignKey("IdActividad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Muni_Bouwer.Entities.Models.Docente", "Docente")
                        .WithMany("DocenteActividades")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Documentacion", b =>
                {
                    b.HasOne("Muni_Bouwer.Entities.Models.Alumno", "Alumno")
                        .WithMany("Documentaciones")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.FichaMedica", b =>
                {
                    b.HasOne("Muni_Bouwer.Entities.Models.Alumno", "Alumno")
                        .WithOne("FichaMedica")
                        .HasForeignKey("Muni_Bouwer.Entities.Models.FichaMedica", "IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Inscripcion", b =>
                {
                    b.HasOne("Muni_Bouwer.Entities.Models.AlumnoActividad", "AlumnoActividad")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdAlumnoActividad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlumnoActividad");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("Muni_Bouwer.Entities.Models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Muni_Bouwer.Entities.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.HasOne("Muni_Bouwer.Entities.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Muni_Bouwer.Entities.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Actividad", b =>
                {
                    b.Navigation("AlumnoActividades");

                    b.Navigation("DocenteActividades");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.AlumnoActividad", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.DocenteActividad", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Alumno", b =>
                {
                    b.Navigation("AlumnoActividades");

                    b.Navigation("Documentaciones");

                    b.Navigation("FichaMedica");
                });

            modelBuilder.Entity("Muni_Bouwer.Entities.Models.Docente", b =>
                {
                    b.Navigation("DocenteActividades");
                });
#pragma warning restore 612, 618
        }
    }
}
